version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo-msAdministrador
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret123
    ports:
      - "27017:27017"
    volumes:
      - mongo-msAdministrador-data:/data/db

  mongo-express:
    image: mongo-express:1.0
    container_name: mongo-express-msAdministrador
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret123
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_SITE_BASEURL: "/"
    ports:
      - "8081:8081"
    depends_on:
      - mongo

volumes:
  mongo-msAdministrador-data:
